apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    size: {{.NegSizeLabel}}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    name: {{.DeploymentBaseName}}-{{.Index}}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
